link generating fixed
Kentico/xperience-by-kentico-zapier pull request #31
Opened 2024-10-14 12:57 UTC by DanielJurcaBS

# Motivation

Fixes link generation to admin UI
aswell as updates xbk to be able to use IPageLinkGenerator

## Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

2024-10-22 14:14 UTC, michalJakubis requested changes
Upgrade also version in https://github.com/Kentico/xperience-by-kentico-zapier/blob/main/examples/DancingGoat/.config/dotnet-tools.json#L6

2024-10-22 14:14 UTC, michalJakubis commented on src/Kentico.Xperience.Zapier/Helpers/AdminUrlHelper.cs
> +            { typeof(WebPageLayout), $"{lang}_{webPageItemId}" },
We can use `new WebPageUrlIdentifier(lang, webPageItemId).ToString()` to generate parameter for `WebPageLayout`.

2024-11-06 12:13 UTC, Rumec approved these changes
Approved

2024-11-06 12:21 UTC, michalJakubis approved these changes

2024-11-06 12:35 UTC, merged