updating APIs, removing obsolete API usage, fixing build warnings
Kentico/xperience-by-kentico-zapier pull request #35
Opened 2024-11-27 08:00 UTC by jiri-malec

# Motivation
 - Fixes issue [`86198608`](https://github.com/orgs/Kentico/projects/14?pane=issue&itemId=86198608)
 - Removing obsolete API, upgrading API references, removing additional build warnings

## Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

## How to test

If manual testing is required, what are the steps?

2024-11-27 13:37 UTC, Rumec requested changes
Look at my proposition, please.

If you have any questions, don't hesitate to ask!

2024-11-27 19:55 UTC, seangwright commented
Just a heads up, I did a lot of this work already in https://github.com/Kentico/xperience-by-kentico-zapier/pull/34

There is some project structured/config that was missing that I also added.

2024-11-28 09:42 UTC, jiri-malec commented
> Just a heads up, I did a lot of this work already in #34
> 
> There is some project structured/config that was missing that I also added.

Thank you for pointing that out! From my perspective, your merge request addresses all the issues I was targeting with this one. Therefore, it might make sense to close this MR and proceed with #34 instead. @Rumec

2024-11-28 11:53 UTC, jiri-malec commented on examples/DancingGoat/Helpers/AreaRestrictionHelper.cs
> +                .Where(id => allowedScopes.ToList().Exists(scope => id.StartsWith(scope, StringComparison.OrdinalIgnoreCase)))
Yes, good point. Since a HashSet has constant-time complexity for lookups, your solution would be more efficient.

2024-12-04 09:31 UTC, closed without merging